services:
  switch:
    build:
      context: ./switch-container
      dockerfile: ./Dockerfile
    command: sleep 10000000
    volumes:
      - /home/brad/Documents/energy-democracy/gridmodel/data/switch/scc7a_60_fuel/:/switchdata/
      - ./volumes/nimbus/:/nimbus

  # http-server:
  #   build: ./http_server/
  #   ports:
  #     - 2718:2718
  #   expose:
  #     - 2718
  #   environment:
  #     - REDIS_HOST = valkey
  #   command: "python3 litestar_server.py"

  valkey:
    hostname: valkey
    image: valkey/valkey:7.2.5
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/valkey-data:/data

