services:
  switch:
    env_file:
      - .env
    build:
      context: ./switch-container
      dockerfile: ./Dockerfile
    command: python3 server_utils.py
    volumes:
      - /home/brad/Documents/energy-democracy/gridmodel/data/switch/scc7a_60_fuel/:/switchdata/
      - ./volumes/nimbus/:/nimbus

  http-server:
    env_file:
      - .env
    build: ./http-server/
    ports:
      - 2718:2718
    expose:
      - 2718
    environment:
      - REDIS_HOST = valkey
    command: "python3 litestar_server.py"

  valkey:
    hostname: valkey
    image: valkey/valkey:7.2.5
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/valkey-data:/data
